### ISSUE TITLE
📦 🔧  Missing Necessary Config in pyproject.toml Config

### ISSUE THREAD

**Issue by ARYAN-NIKNEZHAD** [enzofrnt/django_wait_for_db#7]
### Description
- Commitizen for commit message and changelog and bump versioning 
- Pylint for linting in Python
- black for format
- isort for imports in Python
- Bandit for security in python code
- ruff for format in python codes
- mypy for Python codes

**Comment by ARYAN-NIKNEZHAD** [comment]
You can use my configuration
https://github.com/Lazarus-org/django_logging/blob/main/pyproject.toml

**Comment by enzofrnt** [comment]
I'm trying to understand everything. I'm currently on test, I will take look to these things later.

**Comment by ARYAN-NIKNEZHAD** [comment]
@enzofrnt 
Feel free to join my Telegram channel, where I can share all the details with you directly!
link: https://t.me/+CsoGZH435s82ODlk

**Comment by enzofrnt** [comment]
Everything add, take look in 2 minutes at main
