### ISSUE TITLE
📚 Missing docs files

### ISSUE THREAD

**Issue by ARYAN-NIKNEZHAD** [enzofrnt/django_wait_for_db#8]
## Description

The project is missing the `docs` folder, which should contain `.rst` (reStructuredText) files for documentation. This folder is crucial for generating proper documentation using tools like Sphinx or other documentation generators.

## Expected Behavior

The project should have a `docs/` directory with the following:

1. `index.rst` – The main entry point for the documentation.
2. Other relevant `.rst` files (e.g., `installation.rst`, `usage.rst`, `contributing.rst`, etc.) to cover different aspects of the project.
3. A `conf.py` file to configure the Sphinx documentation generator, if applicable.

## Current Behavior

Currently, there is no `docs/` directory in the project repository, making it difficult to generate or view the documentation.

## Steps to Reproduce

1. Clone the project repository.
2. Navigate through the file structure to check for the presence of a `docs/` folder.
3. Verify the missing `.rst` files and the configuration for documentation.

## Proposed Solution

1. Add a `docs/` folder with at least the basic `.rst` files:
   - `index.rst`
   - `installation.rst`
   - `usage.rst`
   - Any other files necessary for comprehensive project documentation.
   
2. If using Sphinx, include a `conf.py` file to manage the documentation settings.

3. Update the documentation and ensure the README file points to the generated docs.

## Impact

The absence of proper documentation makes it difficult for new users to understand the project setup, installation, and usage instructions. This may affect the project's adoption and contribution rate.

**Comment by enzofrnt** [comment]
Do I really need it for something this little ?

**Comment by ARYAN-NIKNEZHAD** [comment]
Yes, we need documentation in `.rst` format to support the addition of new features to the package.

**Comment by enzofrnt** [comment]
> Yes, we need documentation in `.rst` format to support the addition of new features to the package.

why is it better ?

**Comment by enzofrnt** [comment]
Waiting for explanation

**Comment by ARYAN-NIKNEZHAD** [comment]
@enzofrnt 
It's optional, but for future enhancements and additional settings in the package, it's a good idea to set up ReadTheDocs from the start. This will streamline documentation as the project grows.

**Comment by enzofrnt** [comment]
Will not be add.
